# Generated by Django 5.2.6 on 2025-09-10 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("name", models.CharField(help_text="Full name of the student", max_length=255)),
                ("birth_date", models.DateField(help_text="Date of birth of the student")),
                (
                    "extra_info",
                    models.TextField(blank=True, help_text="Additional information about the student", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("former", "Former")],
                        default="active",
                        help_text="Current status of the student",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "management_students",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("name", models.CharField(help_text="Full name of the teacher", max_length=255)),
                ("pix_key", models.CharField(help_text="PIX key for payments to the teacher", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("former", "Former")],
                        default="active",
                        help_text="Current status of the teacher",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "management_teachers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentsGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("scheduled_at", models.DateTimeField(help_text="Scheduled date and time for the group lessons")),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of students allowed in this group",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        help_text="Students enrolled in this group", related_name="groups", to="management.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher assigned to this group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="management.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Students Group",
                "verbose_name_plural": "Students Groups",
                "db_table": "management_students_groups",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("occurred_at", models.DateTimeField(help_text="Date and time when the lesson took place")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the lesson content or student performance", null=True
                    ),
                ),
                (
                    "students_group",
                    models.ForeignKey(
                        help_text="Group this lesson belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="management.studentsgroup",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who conducted the lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="management.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "db_table": "management_lessons",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product or course the student is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="comercial.product",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student enrolled in the contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="management.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "management_contracts",
                "ordering": ["-created_at"],
                "unique_together": {("student", "product")},
            },
        ),
    ]
