# Generated by Django 5.2.6 on 2025-09-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students enrolled in this group",
                null=True,
                related_name="groups",
                to="management.student",
            ),
        ),
    ]
