# Generated by Django 5.2.6 on 2025-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_studentsgroup_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="first_lesson_on",
            field=models.DateField(blank=True, help_text="Date of the first lesson", null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="last_lesson_on",
            field=models.DateField(blank=True, help_text="Date of the last lesson", null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("credit_card", "Credit Card"), ("pix", "PIX"), ("boleto", "Boleto")],
                help_text="Method used for the payment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="statements",
            field=models.IntegerField(blank=True, help_text="Number of statements for the contract", null=True),
        ),
        migrations.AlterField(
            model_name="studentsgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, help_text="Students enrolled in this group", related_name="groups", to="management.student"
            ),
        ),
    ]
