# Generated by Django 5.2.6 on 2025-09-10 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("credit_card", "Credit Card"), ("pix", "PIX"), ("boleto", "Boleto")],
                        help_text="Method used for the payment",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid in local currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("paid_at", models.DateTimeField(help_text="Timestamp when the payment was completed")),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description or reference for the payment", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "financial_payments",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherPayments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid to the teacher in local currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("paid_at", models.DateTimeField(help_text="Timestamp when the payment was completed")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("credit_card", "Credit Card"), ("pix", "PIX"), ("boleto", "Boleto")],
                        help_text="Method used for the payment",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description or reference for the payment", max_length=255, null=True
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who received the payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="management.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Payment",
                "verbose_name_plural": "Teacher Payments",
                "db_table": "financial_teacher_payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
