# Generated by Django 5.2.6 on 2025-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("name", models.CharField(help_text="Name of the product or course", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of the product", null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price of the product in local currency", max_digits=10
                    ),
                ),
                ("duration_months", models.PositiveIntegerField(help_text="Duration of the product in months")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the product is currently available for enrollment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "comercial_products",
                "ordering": ["name"],
            },
        ),
    ]
