# Generated by Django 5.2.6 on 2025-09-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="duration",
        ),
        migrations.AddField(
            model_name="product",
            name="duration",
            field=models.PositiveIntegerField(default=24, help_text="Duration of the product in lessons"),
        ),
    ]
