# Generated by Django 5.2.6 on 2025-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Timestamp when the record was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Timestamp when the record was last updated"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when the record was soft deleted", null=True),
                ),
                ("name", models.CharField(help_text="Full name of the lead", max_length=255)),
                ("goals", models.TextField(help_text="Goals and objectives of the lead")),
                ("birth_date", models.DateField(help_text="Date of birth of the lead")),
                (
                    "interests",
                    models.TextField(
                        blank=True,
                        help_text="Areas of interest or specific courses the lead is interested in",
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, help_text="Email address of the lead", max_length=254, null=True),
                ),
                ("phone", models.CharField(blank=True, help_text="Phone number of the lead", max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "crm_leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
